"""Generates a Protobuf v3 .proto file (as text) from the IR.

Notes on design decisions:
- Field numbers are assigned sequentially in declaration order, starting
  at 1. This is fine for a freshly generated schema; if/when this tool
  grows schema-evolution support, field numbers will need to be pinned
  across regenerations rather than recomputed (see ROADMAP.md).
- "required" has no meaning in proto3 (all fields are technically
  optional on the wire); we use the `optional` keyword for fields marked
  not-required, which gives them explicit presence tracking, matching
  proto3's modern style.
- Avro/JSON Schema "map" types map directly to proto3 `map<string, V>`.
"""

from __future__ import annotations

from ..ir import Field, FieldKind, RecordType, Schema

_PRIMITIVE_MAP = {
    FieldKind.STRING: "string",
    FieldKind.INT: "int32",
    FieldKind.LONG: "int64",
    FieldKind.FLOAT: "float",
    FieldKind.DOUBLE: "double",
    FieldKind.BOOL: "bool",
    FieldKind.BYTES: "bytes",
    # google.protobuf.Timestamp would be more idiomatic, but that drags in
    # a well-known-types import; keep it simple and use int64 epoch-millis
    # with a comment, matching the "no surprise imports" philosophy.
    FieldKind.TIMESTAMP: "int64",
}


class _FieldNumberer:
    def __init__(self):
        self._n = 0

    def next(self) -> int:
        self._n += 1
        return self._n


def generate(schema: Schema) -> str:
    lines: list[str] = []
    lines.append('syntax = "proto3";')
    lines.append("")
    lines.append(f"package {schema.namespace.replace('.', '_')};")
    lines.append("")
    lines.append(f"// Generated by schemalattice v{schema.version} — do not edit by hand.")
    lines.append("// Source of truth lives in the .sl.yaml schema file.")
    lines.append("")

    nested_messages: list[str] = []
    nested_enums: list[str] = []
    main = _record_to_proto(schema.root, nested_messages, nested_enums, top_level=True)

    lines.extend(nested_enums)
    lines.extend(nested_messages)
    lines.append(main)
    return "\n".join(lines) + "\n"


def _record_to_proto(record: RecordType, nested_messages: list[str], nested_enums: list[str], top_level: bool = False) -> str:
    numberer = _FieldNumberer()
    body_lines = []

    if record.doc:
        body_lines.append(f"  // {record.doc}")

    for f in record.fields:
        body_lines.append(_field_to_proto_line(f, numberer, nested_messages, nested_enums))

    header = f"message {record.name} {{"
    body = "\n".join(body_lines)
    return f"{header}\n{body}\n}}\n"


def _field_to_proto_line(f: Field, numberer: _FieldNumberer, nested_messages: list[str], nested_enums: list[str]) -> str:
    num = numberer.next()
    comment = f"  // {f.doc}" if f.doc else ""

    if f.kind in _PRIMITIVE_MAP:
        type_name = _PRIMITIVE_MAP[f.kind]
        modifier = "" if f.required else "optional "
        return f"  {modifier}{type_name} {f.name} = {num};{comment}"

    if f.kind == FieldKind.ENUM:
        enum_block = _enum_to_proto(f.enum)
        nested_enums.append(enum_block)
        modifier = "" if f.required else "optional "
        return f"  {modifier}{f.enum.name} {f.name} = {num};{comment}"

    if f.kind == FieldKind.RECORD:
        nested_messages.append(_record_to_proto(f.record, nested_messages, nested_enums))
        modifier = "" if f.required else "optional "
        return f"  {modifier}{f.record.name} {f.name} = {num};{comment}"

    if f.kind == FieldKind.ARRAY:
        item = f.item
        if item.kind == FieldKind.RECORD:
            nested_messages.append(_record_to_proto(item.record, nested_messages, nested_enums))
            type_name = item.record.name
        elif item.kind == FieldKind.ENUM:
            nested_enums.append(_enum_to_proto(item.enum))
            type_name = item.enum.name
        else:
            type_name = _PRIMITIVE_MAP[item.kind]
        return f"  repeated {type_name} {f.name} = {num};{comment}"

    if f.kind == FieldKind.MAP:
        item = f.item
        if item.kind == FieldKind.RECORD:
            nested_messages.append(_record_to_proto(item.record, nested_messages, nested_enums))
            value_type = item.record.name
        elif item.kind == FieldKind.ENUM:
            nested_enums.append(_enum_to_proto(item.enum))
            value_type = item.enum.name
        else:
            value_type = _PRIMITIVE_MAP[item.kind]
        return f"  map<string, {value_type}> {f.name} = {num};{comment}"

    raise ValueError(f"unhandled field kind: {f.kind}")


def _enum_to_proto(enum) -> str:
    lines = [f"enum {enum.name} {{"]
    # proto3 requires the first enum value to be 0
    lines.append(f"  {enum.name.upper()}_UNSPECIFIED = 0;")
    for i, val in enumerate(enum.values, start=1):
        lines.append(f"  {val} = {i};")
    lines.append("}\n")
    return "\n".join(lines)
